In [2]:
import numpy


In [3]:
n=numpy.arange(27)

In [4]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [5]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [6]:
import cv2


In [7]:
i=cv2.imread('robot.jpg')
print(i)

[[[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 ...

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]]


image dimensiona

In [8]:
i[0:4,2:3]

array([[[240, 244, 245]],

       [[240, 244, 245]],

       [[240, 244, 245]],

       [[240, 244, 245]]], dtype=uint8)

pixels in loops img source

In [30]:
for j in i:
    print(i)

[[[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 ...

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]]
[[[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 ...

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ..

  [240 244 245]]]
[[[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 ...

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]]
[[[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 ...

 [[240 244 245]
  [240 244 245]
  

  [240 244 245]]]
[[[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 ...

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]]
[[[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 [[240 244 245]
  [240 244 245]
  [240 244 245]
  ...
  [240 244 245]
  [240 244 245]
  [240 244 245]]

 ...

 [[240 244 245]
  [240 244 245]
  

In [33]:
import numpy as np

In [34]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
import math
import matplotlib.pyplot as plt

In [39]:
x=np.arange(0,math.pi*2,0.05)
y=np.sin(x)
plt(x,y)